### ISSUE TITLE
bug: _redirects parsing error does not provide enough info

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/go-libipfs#280] opened 2023-04-16 11:24 UTC
do we have a _redirects file CLI validator or other way to verify that my _redirects file can be parsed correctly and that I can confirm (before deployment) that i’m not going to get the following error: `could not parse _redirects: %!w(<nil>)` ?

https://specs.ipfs.tech/http-gateways/web-redirects-file/ doesn’t tell me what characters are valid or not, nor how to validate my _redirects, only gives me examples of things I can read to infer what should and shouldn’t be valid.

example: https://bafybeia5sw62acdkkicvommwb2zeomlctc2i2ad5qanwa262p4jvvilh2q.ipfs.dweb.link/helia-sw/foobar123

### _redirects file content

```text
╰─ ✔ ❯ cat public/_redirects
/helia-sw/* /index.html/#:splat 302
```

**Comment by SgtPooki** [comment] 2023-04-16 14:21
So, I had an invalid build process which created `_redirects/_redirects` in my `dist` folder.. so the website at CID `bafybeia5sw62acdkkicvommwb2zeomlctc2i2ad5qanwa262p4jvvilh2q` doesn't have a valid `_redirects` file (however,  the error should be more explicit). However, for your info, see below:

```bash
> ipfs ls bafybeia5sw62acdkkicvommwb2zeomlctc2i2ad5qanwa262p4jvvilh2q
bafkreihk2ej2wz3ojqv6ozld2vjs4rt5umvvxanplvqrt6zvq25hxo2pri 134665  574.js
bafkreieuc4czozfemmp2epvn2elm6ceoqevb7zrvnizpmql47mvpuvycau 75104   574.js.gz
bafybeib6mtbfprje3zgnpuos3dtkthmc44nyzr6wbh3cey5t7ykbvzd7km 1422049 832.js
bafkreiabwevrjgccfjiztx4n3xbdlas7gnpium62r5tn4qp6lbusdgtboi 1088    832.js.LICENSE.txt
bafybeiab6tasfc7riqtt46vzobfftrvqpi6m7f7uvs7c4x6byofals2rki 396309  832.js.gz
bafybeifouj2ytsv3pbto6j5cskjmkdvhx5uulihk5iaxyq5wy5th2mmdoa -       _redirects/
bafkreihc7efnl2prri6j6krcopelxms3xsh7undpsjqbfsasm7ikiyha4i 34494   favicon.ico
bafkreicvl2lf4ssc4ylt3q6qxdjisdxvhormmwyxt6f72hf7kia2noxwbe 635     index.html
bafkreici4bhf6uuzmx26ntykc6s3om5hmebyjvwdrgzxqezaq4loyomuqu 372     index.html.gz
bafybeid3prcp5hch7kzearokqgpp7hsbh55vvq4bontg5lp2ijxndcqkgq 1631042 main.js
bafkreiagmzlcdeqxcevdeijzkrqg6q5rb6sk3ynrxzd765kmijbouyff6u 1810    main.js.LICENSE.txt
bafybeiamxdeof2at3p4kaxpdb2qrch36cw35iuzfhmxgzpfy2buywsiywq 501849  main.js.gz
bafybeiaiefnwlhzcy3eb3e2ift3bml2xtgmhyt37ixg7pfwyb5zfbui5ua 1556926 sw.js
bafkreiabwevrjgccfjiztx4n3xbdlas7gnpium62r5tn4qp6lbusdgtboi 1088    sw.js.LICENSE.txt
bafybeie5nmf5iodrincula4irotwyfprstwbqp4p6uj4lvvobyntawjnpu 471016  sw.js.gz
```

`bafybeif6jbi63wcxslh73wxyg4wu3eobf5c2wweyvzge46juuwka2r54yy` has a valid _redirects file and solves my issue, but the error messaging (**Specifically when reading _redirects as a file doesn't work properly**) should still be addressed

```bash
> ipfs ls bafybeif6jbi63wcxslh73wxyg4wu3eobf5c2wweyvzge46juuwka2r54yy
bafkreihk2ej2wz3ojqv6ozld2vjs4rt5umvvxanplvqrt6zvq25hxo2pri 134665  574.js
bafkreieuc4czozfemmp2epvn2elm6ceoqevb7zrvnizpmql47mvpuvycau 75104   574.js.gz
bafybeib6mtbfprje3zgnpuos3dtkthmc44nyzr6wbh3cey5t7ykbvzd7km 1422049 832.js
bafkreiabwevrjgccfjiztx4n3xbdlas7gnpium62r5tn4qp6lbusdgtboi 1088    832.js.LICENSE.txt
bafybeiab6tasfc7riqtt46vzobfftrvqpi6m7f7uvs7c4x6byofals2rki 396309  832.js.gz
bafkreidtglv5z7eeswwlmwm7ybalvlry4kgny6dyi5eqlgxgd37gnxryge 34      _redirects
bafkreihc7efnl2prri6j6krcopelxms3xsh7undpsjqbfsasm7ikiyha4i 34494   favicon.ico
bafkreicvl2lf4ssc4ylt3q6qxdjisdxvhormmwyxt6f72hf7kia2noxwbe 635     index.html
bafkreici4bhf6uuzmx26ntykc6s3om5hmebyjvwdrgzxqezaq4loyomuqu 372     index.html.gz
bafybeifcc33ykypggwwlb2ojqebwa2i2j74sysce6xtaq73pjqpl6nq23i 1631504 main.js
bafkreiagmzlcdeqxcevdeijzkrqg6q5rb6sk3ynrxzd765kmijbouyff6u 1810    main.js.LICENSE.txt
bafybeihspvky6uqltqoz26btp5ymijjuh2yr6rr4m7lfb4dfjchw2aujmu 502006  main.js.gz
bafybeiaiefnwlhzcy3eb3e2ift3bml2xtgmhyt37ixg7pfwyb5zfbui5ua 1556926 sw.js
bafkreiabwevrjgccfjiztx4n3xbdlas7gnpium62r5tn4qp6lbusdgtboi 1088    sw.js.LICENSE.txt
bafybeie5nmf5iodrincula4irotwyfprstwbqp4p6uj4lvvobyntawjnpu 471016  sw.js.gz
```

**Comment by Jorropo** [comment] 2023-04-16 14:53
It's weird, this shouldn't happen https://github.com/ipfs/boxo/blob/b3b66209c03af58804301c645aee6508b0a357c8/gateway/handler_unixfs__redirects.go#L171-L173 I think we have a typed nil issue.

**Comment by lidel** [comment] 2023-04-20 20:21
Either way, if `/ipfs/cid/_redirects` is a directory and not a file, it should either be ignored, or produce a clear error stating that it should be a file :)

@hacdias @justindotpub thoughts?

**Comment by justindotpub** [comment] 2023-04-25 12:21
@lidel I am no longer actively working on IPFS.  I might be able to look at this later, but please don't rely on me for this.  Thanks.

**Comment by hacdias** [comment] 2023-05-02 13:51
I cannot reproduce the error gotten by @SgtPooki:

1. If `_redirects` is a directory, I get `trouble processing _redirects file at /file/path: _redirects is not a file`
	2. Already fails like @lidel suggested. We should add a test for this.
3. Invalid rules just give me an error on why the rule is invalid

What Kubo version did you use?

To note that I created a local repository locally and tried to reproduce as best as I could locally. `bafybeia5sw62acdkkicvommwb2zeomlctc2i2ad5qanwa262p4jvvilh2q` can't be fetched.

**Comment by SgtPooki** [comment] 2023-05-09 05:13
Let me see if i can repro with the latest

**Comment by hacdias** [comment] 2023-05-09 14:27
Any updates @SgtPooki ?

**Comment by BigLep** [comment] 2023-05-11 02:01
Closing for now.  We'll reopen if a repo can be found.

**Closed as completed by BigLep** 2023-05-11 02:01 UTC
Labels: P2, kind/bug, topic/gateway

**Comment by SgtPooki** [comment] 2023-05-11 18:56
confirmed the error message is better using latest kubo from `master` branch, built locally.. I get:

![image](https://github.com/ipfs/boxo/assets/1173416/e0ab6110-107f-4ef2-91fa-1f1221d001e5)

> trouble processing _redirects file at "/ipfs/bafybeia5sw62acdkkicvommwb2zeomlctc2i2ad5qanwa262p4jvvilh2q/_redirects":  _redirects is not a file

seems like it's resolved.
